[tool.poetry]
name = "weatherstackwrapper"
version = "0.1.0"
description = "Python wrapper for the weather stack api"
authors = ["Darien Moore <LiskIsBest@gmail.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.6"
httpx = "^0.23.3"
pydantic = "^1.10.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
